### ISSUE TITLE
how use lazy loading in FlatList?

### ISSUE THREAD

**Issue by DavitVosk** [soldotno/react-native-lazyload-deux#11]
In the documentation it is mentioned that FlatList solves all our needs and that is why there is no need for this package. Can you please describe how can I handle image lazy loading in FlatList? I could not find anything in its documentation. Thanks in advance

**Comment by engvik** [comment]
Sorry, I haven't seen this until now.

You've probably figured it out, but [here's an example](https://stackoverflow.com/questions/49648292/how-to-apply-lazy-loading-in-flatlist-in-react-native)
